import { StyleSheet } from 'react-native';
import {
  cardTitleColor,
  cardSubtitleColor,
  cardContentColor,
  cardHighlightColor,
  titleFontSize,
  subtitleFontSize,
  contentFontSize,
  titleFont,
  contentFont,
  lineHeight,
  lineSpacing,
  cardMargin,
  jumboFontSize,
  textInputMargin,
  cardBackgroundColor,
  textInputContainerHeight,
  cardShadowColor,
  headerBackgroundColor,
  screenWidth,
  screenHeight,
} from '../../styles/common';

export default StyleSheet.create({
  tabContainer: {
    backgroundColor: cardBackgroundColor,
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  containerShadow: {
    paddingBottom: textInputMargin * 2,
    backgroundColor: cardShadowColor,
  },
  tabTitle: {
    color: cardSubtitleColor,
    fontSize: subtitleFontSize,
    fontFamily: titleFont,
    marginLeft: 60,
    marginRight: 60,
  },
  tabTitleActive: {
    color: headerBackgroundColor,
    fontSize: subtitleFontSize,
    fontFamily: titleFont,
    marginLeft: 60,
    marginRight: 60,
  },
  cardSection: {
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: cardMargin,
    marginRight: cardMargin,
  },
  containerSpaceBetween: {
    marginTop: textInputMargin * 2,
    marginBottom: textInputMargin * 2,
  },
  cardTitle: {
    color: cardTitleColor,
    fontSize: jumboFontSize,
    fontFamily: titleFont,
  },
  cardSubtitle: {
    color: cardSubtitleColor,
    fontSize: subtitleFontSize,
    fontFamily: titleFont,
  },
  cardTitleActive: {
    color: headerBackgroundColor,
    fontSize: jumboFontSize,
    fontFamily: titleFont,
  },
  cardSubtitleActive: {
    color: headerBackgroundColor,
    fontSize: subtitleFontSize,
    fontFamily: titleFont,
  },
  cardTitleHidden: {
    color: 'transparent',
    fontSize: jumboFontSize,
    fontFamily: titleFont,
  },
  cardSubtitleHidden: {
    color: 'transparent',
    fontSize: subtitleFontSize,
    fontFamily: titleFont,
  },
  cardSubtitleDark: {
    color: cardTitleColor,
    fontSize: subtitleFontSize * 1.2,
    fontFamily: titleFont,
  },
  cardContent: {
    color: cardContentColor,
    fontSize: contentFontSize,
    lineHeight: lineHeight,
    marginTop: lineSpacing,
    marginBottom: lineSpacing,
    fontFamily: contentFont,
  },
  cardHighlight: {
    backgroundColor: cardHighlightColor,
    padding: lineSpacing,
  },
  modalContainer: {
    flex: 1,
    alignItems: 'center',
    marginTop: 50,
    marginBottom: 50,
  },
  modalBackgroundContainer: {
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
    height: 350,
    width: 300,
    borderRadius: 10,
  },
  closeButton: {
    marginTop: lineHeight,
    marginRight: lineHeight,
    color: cardBackgroundColor,
    fontSize: jumboFontSize - 10,
    fontFamily: titleFont,
    textAlign: 'right',
  },
  modalTitle: {
    marginTop: lineHeight,
    marginBottom: lineHeight,
    color: cardBackgroundColor,
    fontSize: titleFontSize,
    fontFamily: titleFont,
    textAlign: 'center',
  },
  modalContent: {
    marginTop: lineHeight,
    color: cardBackgroundColor,
    fontSize: subtitleFontSize - 5,
    fontFamily: contentFont,
    textAlign: 'center',
  }
});
