import { StyleSheet } from 'react-native';
import {
  cardTitleColor,
  cardSubtitleColor,
  cardContentColor,
  cardHighlightColor,
  jumboFontSize,
  titleFontSize,
  subtitleFontSize,
  contentFontSize,
  titleFont,
  contentFont,
  lineHeight,
  lineSpacing,
  cardMargin,
  cardBackgroundColor,
  cardShadowColor,
  cardButtonActiveColor,
  textInputMargin,
  headerBackgroundColor,
} from '../../styles/common';

export default StyleSheet.create({
  cardSection: {
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: cardMargin,
    marginRight: cardMargin,
  },
  cardTitle: {
    color: cardTitleColor,
    fontSize: jumboFontSize,
    fontFamily: titleFont,
  },
  cardSubtitle: {
    color: cardSubtitleColor,
    fontSize: subtitleFontSize,
    fontFamily: titleFont,
  },
  cardContent: {
    color: cardContentColor,
    fontSize: contentFontSize,
    lineHeight: lineHeight,
    marginTop: lineSpacing,
    marginBottom: lineSpacing,
    fontFamily: contentFont,
  },
  cardHighlight: {
    backgroundColor: cardHighlightColor,
    padding: lineSpacing,
  },
  switchContainerActiveTop: {
    height: 35,
    width: 25,
    backgroundColor: cardButtonActiveColor,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  switchContainerTop: {
    height: 35,
    width: 25,
    backgroundColor: cardTitleColor,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  switchContainerActiveBottom: {
    height: 35,
    width: 25,
    backgroundColor: cardButtonActiveColor,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  switchContainerBottom: {
    height: 35,
    width: 25,
    backgroundColor: cardTitleColor,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  switchContainerHidden: {
    height: 35,
    width: 25,
    backgroundColor: cardBackgroundColor,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardSwitchContent: {
    color: cardSubtitleColor,
    fontSize: subtitleFontSize - 3,
    fontFamily: titleFont,
  },
  cardSwitchContentHidden: {
    color: 'transparent',
    fontSize: subtitleFontSize - 3,
    fontFamily: titleFont,
  },
  cardContentSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabContainer: {
    backgroundColor: cardBackgroundColor,
    height: 50,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerShadow: {
    paddingBottom: textInputMargin * 2,
    backgroundColor: cardShadowColor,
  },
  tabTitle: {
    color: cardSubtitleColor,
    fontSize: subtitleFontSize,
    fontFamily: titleFont,
  },
  cardSubtitleDark: {
    color: cardTitleColor,
    fontSize: subtitleFontSize * 1.2,
    fontFamily: titleFont,
  },
  modalContainer: {
    flex: 1,
    alignItems: 'center',
    marginTop: 50,
    marginBottom: 50,
  },
  modalBackgroundContainer: {
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
    height: 350,
    width: 300,
    borderRadius: 10,
  },
  closeButton: {
    marginTop: lineHeight,
    marginRight: lineHeight,
    color: cardBackgroundColor,
    fontSize: jumboFontSize - 10,
    fontFamily: titleFont,
    textAlign: 'right',
  },
  modalTitle: {
    marginTop: lineHeight,
    marginBottom: lineHeight,
    color: cardBackgroundColor,
    fontSize: titleFontSize,
    fontFamily: titleFont,
    textAlign: 'center',
  },
  modalContent: {
    marginTop: lineHeight,
    color: cardBackgroundColor,
    fontSize: subtitleFontSize - 5,
    fontFamily: contentFont,
    textAlign: 'center',
  }
});
